// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDb))]
    [Migration("20231222020513_setup")]
    partial class setup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AnimalModel.Animal", b =>
                {
                    b.Property<Guid>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AnimalId");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.ToTable("Animal");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.UserAnimalModel.UsersHaveAnimals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UsersHaveAnimals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AnimalId = new Guid("12345678-1234-5678-1234-567812345682"),
                            UserId = new Guid("08260479-52a0-4c0e-a588-274101a2c3be")
                        },
                        new
                        {
                            Id = -2,
                            AnimalId = new Guid("12345680-1224-5878-1234-667812345690"),
                            UserId = new Guid("08260479-52a0-4c0e-a588-274101a2c3be")
                        },
                        new
                        {
                            Id = -3,
                            AnimalId = new Guid("12345678-1234-5678-1234-567812345682"),
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036868")
                        },
                        new
                        {
                            Id = -4,
                            AnimalId = new Guid("12345680-1224-5878-1234-667812345690"),
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036868")
                        });
                });

            modelBuilder.Entity("Domain.Models.UserModel.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnimalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("08260479-52a0-4c0e-a588-274101a2c3be"),
                            Password = "$2a$11$WyqaeU.YeLlrYqo7sDlDIOty0sIzpkG3l.W1rxX..Ho9g882nR4RO",
                            Role = "admin",
                            Username = "Bojan"
                        },
                        new
                        {
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036868"),
                            Password = "$2a$11$3zu0cm.HElaHpTsdEOrP.Ob3Ev9ggpkMfY6OFdpnTZy/F.sYXWNTa",
                            Role = "user",
                            Username = "NotAnAdmin"
                        },
                        new
                        {
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036869"),
                            Password = "$2a$11$qWEsMalco3HiM.tEQst5We3mGrReV/7V0S/0QAI0xjLjAkWfLF/su",
                            Role = "user",
                            Username = "TestUser"
                        });
                });

            modelBuilder.Entity("Domain.Models.AnimalModel.Bird", b =>
                {
                    b.HasBaseType("Domain.Models.AnimalModel.Animal");

                    b.Property<bool>("CanFly")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Birds", (string)null);

                    b.HasData(
                        new
                        {
                            AnimalId = new Guid("10c9e943-49e7-44cb-bd06-c809185438dd"),
                            AnimalType = "",
                            Name = "Ara",
                            CanFly = false,
                            Color = "Red"
                        },
                        new
                        {
                            AnimalId = new Guid("c4feb719-e1a4-47c5-a278-c2e94fcc54be"),
                            AnimalType = "",
                            Name = "Vrana",
                            CanFly = true,
                            Color = "Black"
                        },
                        new
                        {
                            AnimalId = new Guid("2d4e07c0-4277-4779-bee7-8ac4a6fa331e"),
                            AnimalType = "",
                            Name = "Sova",
                            CanFly = true,
                            Color = "Grey"
                        },
                        new
                        {
                            AnimalId = new Guid("12345678-1234-5678-1234-567812345682"),
                            AnimalType = "",
                            Name = "TestBirdForUnitTestBird1",
                            CanFly = false,
                            Color = "blue"
                        },
                        new
                        {
                            AnimalId = new Guid("12345680-1224-5878-1234-667812345690"),
                            AnimalType = "",
                            Name = "TestBirdForUnitTestBird2",
                            CanFly = false,
                            Color = "blue"
                        });
                });

            modelBuilder.Entity("Domain.Models.AnimalModel.Cat", b =>
                {
                    b.HasBaseType("Domain.Models.AnimalModel.Animal");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.ToTable("Cats", (string)null);

                    b.HasData(
                        new
                        {
                            AnimalId = new Guid("5a0eaeb0-7dd3-4100-aa79-f0add7c49d67"),
                            AnimalType = "",
                            Name = "Kity",
                            Breed = "Persian Cat",
                            LikesToPlay = true,
                            Weight = 4
                        },
                        new
                        {
                            AnimalId = new Guid("968dea87-60e2-4093-a191-d77e6a41e033"),
                            AnimalType = "",
                            Name = "Micko",
                            Breed = "Domestic Cat",
                            LikesToPlay = true,
                            Weight = 6
                        },
                        new
                        {
                            AnimalId = new Guid("f9d68585-a161-4087-8373-fe70a7b59eb0"),
                            AnimalType = "",
                            Name = "Azrael",
                            Breed = "Siamese Cat",
                            LikesToPlay = false,
                            Weight = 6
                        },
                        new
                        {
                            AnimalId = new Guid("12345678-1234-5678-1234-567812345680"),
                            AnimalType = "",
                            Name = "TestCatForUnitTests",
                            Breed = "Domestic Cat",
                            LikesToPlay = false,
                            Weight = 6
                        });
                });

            modelBuilder.Entity("Domain.Models.AnimalModel.Dog", b =>
                {
                    b.HasBaseType("Domain.Models.AnimalModel.Animal");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.ToTable("Dogs", (string)null);

                    b.HasData(
                        new
                        {
                            AnimalId = new Guid("93a5f790-f162-4e19-9fd8-8018e1cbc259"),
                            AnimalType = "",
                            Name = "Astor",
                            Breed = "English Pointer",
                            Weight = 28
                        },
                        new
                        {
                            AnimalId = new Guid("d54d24c3-975a-413e-b2b5-55e57cc0a878"),
                            AnimalType = "",
                            Name = "Ari",
                            Breed = "English Pointer",
                            Weight = 31
                        },
                        new
                        {
                            AnimalId = new Guid("5e2efcf6-072b-4838-914c-a4c39cf10ded"),
                            AnimalType = "",
                            Name = "Max",
                            Breed = "German Shepherd",
                            Weight = 37
                        },
                        new
                        {
                            AnimalId = new Guid("12345678-1234-5678-1234-567812345678"),
                            AnimalType = "",
                            Name = "TestDogForUnitTests",
                            Breed = "German Terrire",
                            Weight = 9
                        });
                });

            modelBuilder.Entity("Domain.Models.UserModel.User", b =>
                {
                    b.HasOne("Domain.Models.AnimalModel.Animal", null)
                        .WithMany("Users")
                        .HasForeignKey("AnimalId");
                });

            modelBuilder.Entity("Domain.Models.AnimalModel.Bird", b =>
                {
                    b.HasOne("Domain.Models.AnimalModel.Animal", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.AnimalModel.Bird", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.AnimalModel.Cat", b =>
                {
                    b.HasOne("Domain.Models.AnimalModel.Animal", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.AnimalModel.Cat", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.AnimalModel.Dog", b =>
                {
                    b.HasOne("Domain.Models.AnimalModel.Animal", null)
                        .WithOne()
                        .HasForeignKey("Domain.Models.AnimalModel.Dog", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.AnimalModel.Animal", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
